

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Conference : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Conference entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Conference()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Conference(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Conference> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Conference.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Conference_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Conference_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateFrom
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.DateFrom);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.DateFrom, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateFrom_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateFrom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateFrom_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateTo
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.DateTo);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.DateTo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Place
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Place);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Place, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Place_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Place_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Place_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double GoldMin
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.GoldMin);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.GoldMin, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GoldMin_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GoldMin_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GoldMin_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double SilverMin
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.SilverMin);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.SilverMin, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SilverMin_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SilverMin_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SilverMin_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double BronzeMin
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.BronzeMin);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.BronzeMin, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BronzeMin_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BronzeMin_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BronzeMin_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Active
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Active);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Active, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Conference.DetailsClass.SetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Deadline> Deadlines
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Deadlines);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Deadline> DeadlinesQuery
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetQuery(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Deadlines);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Participation> Participations
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetValue(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Participations);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Participation> ParticipationsQuery
        {
            get
            {
                return global::LightSwitchApplication.Conference.DetailsClass.GetQuery(this, global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Participations);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Conference,
                global::LightSwitchApplication.Conference.DetailsClass,
                global::LightSwitchApplication.Conference.DetailsClass.IImplementation,
                global::LightSwitchApplication.Conference.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass>.Entry
                __ConferenceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass>.Entry(
                    global::LightSwitchApplication.Conference.DetailsClass.__Conference_CreateNew,
                    global::LightSwitchApplication.Conference.DetailsClass.__Conference_Created,
                    global::LightSwitchApplication.Conference.DetailsClass.__Conference_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Conference __Conference_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Conference> es)
            {
                return new global::LightSwitchApplication.Conference(es);
            }
            private static void __Conference_Created(global::LightSwitchApplication.Conference e)
            {
                e.Conference_Created();
            }
            private static bool __Conference_AllowSaveWithErrors(global::LightSwitchApplication.Conference e)
            {
                bool result = false;
                e.Conference_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Conference.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime> DateFrom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.DateFrom) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime> DateTo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.DateTo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string> Place
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Place) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double> GoldMin
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.GoldMin) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double> SilverMin
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.SilverMin) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double> BronzeMin
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.BronzeMin) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, bool> Active
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Active) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Deadline> Deadlines
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Deadlines) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Deadline>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Participation> Participations
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Participations) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Participation>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.DateTime DateFrom { get; set; }
                new global::System.DateTime DateTo { get; set; }
                new string Place { get; set; }
                new string Description { get; set; }
                new double GoldMin { get; set; }
                new double SilverMin { get; set; }
                new double BronzeMin { get; set; }
                new bool Active { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Deadlines { get; }
                new global::System.Collections.IEnumerable Participations { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, int>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>.Entry
                    DateFrom = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>.Entry(
                        "DateFrom",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateFrom_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateFrom_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateFrom_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateFrom_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateFrom_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateFrom_OnValueChanged);
                private static void _DateFrom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._DateFrom, sf);
                }
                private static bool _DateFrom_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.DateFrom_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateFrom_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateFrom_Validate(r);
                }
                private static global::System.DateTime _DateFrom_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.DateFrom;
                }
                private static void _DateFrom_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateFrom = global::LightSwitchApplication.Conference.DetailsClass.TruncateDate(v);
                }
                private static void _DateFrom_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.DateFrom_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>.Entry
                    DateTo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>.Entry(
                        "DateTo",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateTo_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateTo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateTo_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateTo_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateTo_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._DateTo_OnValueChanged);
                private static void _DateTo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._DateTo, sf);
                }
                private static bool _DateTo_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.DateTo_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateTo_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateTo_Validate(r);
                }
                private static global::System.DateTime _DateTo_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.DateTo;
                }
                private static void _DateTo_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateTo = global::LightSwitchApplication.Conference.DetailsClass.TruncateDate(v);
                }
                private static void _DateTo_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.DateTo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Entry
                    Place = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Entry(
                        "Place",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Place_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Place_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Place_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Place_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Place_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Place_OnValueChanged);
                private static void _Place_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._Place, sf);
                }
                private static bool _Place_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.Place_IsReadOnly(ref result);
                    return result;
                }
                private static void _Place_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Place_Validate(r);
                }
                private static string _Place_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.Place;
                }
                private static void _Place_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Place = v;
                }
                private static void _Place_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.Place_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Entry
                    GoldMin = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Entry(
                        "GoldMin",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._GoldMin_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._GoldMin_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._GoldMin_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._GoldMin_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._GoldMin_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._GoldMin_OnValueChanged);
                private static void _GoldMin_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._GoldMin, sf);
                }
                private static bool _GoldMin_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.GoldMin_IsReadOnly(ref result);
                    return result;
                }
                private static void _GoldMin_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.GoldMin_Validate(r);
                }
                private static double _GoldMin_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.GoldMin;
                }
                private static void _GoldMin_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, double v)
                {
                    d.ImplementationEntity.GoldMin = v;
                }
                private static void _GoldMin_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.GoldMin_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Entry
                    SilverMin = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Entry(
                        "SilverMin",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._SilverMin_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._SilverMin_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._SilverMin_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._SilverMin_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._SilverMin_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._SilverMin_OnValueChanged);
                private static void _SilverMin_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._SilverMin, sf);
                }
                private static bool _SilverMin_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.SilverMin_IsReadOnly(ref result);
                    return result;
                }
                private static void _SilverMin_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SilverMin_Validate(r);
                }
                private static double _SilverMin_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.SilverMin;
                }
                private static void _SilverMin_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, double v)
                {
                    d.ImplementationEntity.SilverMin = v;
                }
                private static void _SilverMin_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.SilverMin_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Entry
                    BronzeMin = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Entry(
                        "BronzeMin",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._BronzeMin_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._BronzeMin_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._BronzeMin_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._BronzeMin_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._BronzeMin_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._BronzeMin_OnValueChanged);
                private static void _BronzeMin_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._BronzeMin, sf);
                }
                private static bool _BronzeMin_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.BronzeMin_IsReadOnly(ref result);
                    return result;
                }
                private static void _BronzeMin_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.BronzeMin_Validate(r);
                }
                private static double _BronzeMin_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.BronzeMin;
                }
                private static void _BronzeMin_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, double v)
                {
                    d.ImplementationEntity.BronzeMin = v;
                }
                private static void _BronzeMin_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.BronzeMin_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, bool>.Entry
                    Active = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, bool>.Entry(
                        "Active",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Active_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Active_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Active_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Active_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Active_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Active_OnValueChanged);
                private static void _Active_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._Active, sf);
                }
                private static bool _Active_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.Active_IsReadOnly(ref result);
                    return result;
                }
                private static void _Active_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Active_Validate(r);
                }
                private static bool _Active_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.Active;
                }
                private static void _Active_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.Active = v;
                }
                private static void _Active_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.Active_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Conference e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Conference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Conference.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Conference e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Deadline>.Entry
                    Deadlines = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Deadline>.Entry(
                        "Deadlines",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Deadlines_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Deadlines_GetReferencedEntities,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Deadlines_GetEntityCollection);
                private static void _Deadlines_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Deadline>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._Deadlines, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Deadline> _Deadlines_GetReferencedEntities(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Deadline, global::LightSwitchApplication.Deadline.DetailsClass>(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Deadlines, ref d._Deadlines);
                }
                private static global::System.Collections.IEnumerable _Deadlines_GetEntityCollection(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.Deadlines;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Participation>.Entry
                    Participations = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Participation>.Entry(
                        "Participations",
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Participations_Stub,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Participations_GetReferencedEntities,
                        global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties._Participations_GetEntityCollection);
                private static void _Participations_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Conference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Participation>.Data> c, global::LightSwitchApplication.Conference.DetailsClass d, object sf)
                {
                    c(d, ref d._Participations, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Participation> _Participations_GetReferencedEntities(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Participation, global::LightSwitchApplication.Participation.DetailsClass>(global::LightSwitchApplication.Conference.DetailsClass.PropertySetProperties.Participations, ref d._Participations);
                }
                private static global::System.Collections.IEnumerable _Participations_GetEntityCollection(global::LightSwitchApplication.Conference.DetailsClass d)
                {
                    return d.ImplementationEntity.Participations;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>.Data _DateFrom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.DateTime>.Data _DateTo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Data _Place;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Data _GoldMin;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Data _SilverMin;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, double>.Data _BronzeMin;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, bool>.Data _Active;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Deadline>.Data _Deadlines;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Conference, global::LightSwitchApplication.Conference.DetailsClass, global::LightSwitchApplication.Participation>.Data _Participations;
            
        }
    
        #endregion
    }
    
    #endregion
}
